name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: 'Features'
    labels:
      - 'feature'
      - 'features'
      - 'enhancement'
  - title: 'Bug Fix'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: 'Maintenance'
    labels: 
      - 'chore'
  - title: 'Dependence'
    labels:
      - 'dependencies'
change-template: |
  * $TITLE (#$NUMBER) $HEAD_REF_NAME
replacers:
  - search: '/CVE-(\d{4})-(\d+)/g'
    replace: 'https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-$1-$2'
  - search: '(.*)\:\s(.*)'
    replace: '**$1:** $2'
footer: |
  ***

  $CONTRIBUTORS
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  $CHANGES
