site_name: HydroRollCore 核心文档
repo_url: https://github.com/HydroRoll-Team/HydroRollCore
repo_name: HydroRoll-Team/HydroRollCore
edit_uri: edit/master/docs/
site_author: HsiangNianian
site_description: >-
  一个基于通用规则包标准的规则包加载器

theme:
  name: material
  language: zh
  favicon: images/logo.png
  icon:
    logo: material/book-sync
    repo: fontawesome/brands/git-alt
  custom_dir: material/overrides
  features:
    - content.action.edit
    - content.action.view
    - content.tooltips
    - navigation.footer
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.sections
    # - navigation.expand
    - navigation.path
    - navigation.indexes
    - toc.follow
    - navigation.top
    - search.highlight
    - search.suggest
    - search.share
    - header.autohide
    - navigation.footer
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
  palette:
    scheme: slate
    primary: black
    accent: blue

  font:
    text: Times New
    code: Times New
extra:
  status:
    new: 最近添加
    deprecated: 已被废弃
  version:
    provider: mike
  homepage: https://grps.retrofor.space # hydroroll-team.github.io
  consent:
    title: Cookie 偏好设置
    description: >-
      我们使用Cookie来识别您的重复访问和偏好，以及衡量我们的文档的有效性和用户是否找到他们搜索的内容。在您的同意下，这将帮助我们改善我们的文档。
    actions:
      - accept
      - manage
    cookies:
      analytics:
        name: Google Analytics
        checked: true
      github:
        name: GitHub
        checked: true

  social:
    - icon: fontawesome/brands/github
      link: https://github.com/HydroRoll-Team
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/HydroRollCore/

copyright: >
  Copyright &copy; 2013 - PRESENT. <a href="https://github.com/HydroRoll-Team">HydroRoll-Team</a> –
  <a href="#__consent">管理Cookies</a>

markdown_extensions:
  - pymdownx.snippets:
      auto_append:
        - RulePackage/getStart/getDeeper/Module.md
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: ⚓︎
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: HydroRoll-Team
      repo: HydroRollCore
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - blog
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - git-authors
  - mike:
      version_selector: true
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true
      timezone: Asia/Shanghai
      type: timeago
      custom_format: "%d. %B %Y"
  - git-committers:
      repository: HydroRoll-Team/HydroRollCore
  - minify:
      minify_html: true
nav:
  - 主页: index.md
  - 水系核心:
      - "核心概览": Core/index.md
  - 规则包入门:
      - 概述: RulePackage/intro.md
      - 开始:
          - "类": RulePackage/getStart/class.md
          - "方法": RulePackage/getStart/method.md
          - "属性": RulePackage/getStart/attribute.md
          - 深入:
              - "对象": RulePackage/getStart/getDeeper/object.md
              - "模块": RulePackage/getStart/getDeeper/Module.md
              - "包": RulePackage/getStart/getDeeper/Package.md
      - 实战:
          - "了解Python": RulePackage/Write/python.md
          - "准备规则书": RulePackage/Write/prepare.md
          - "编写规则包": RulePackage/Write/write.md
      - 技巧:
          - RulePackage/skill/index.md
          - "善用语法糖": RulePackage/skill/fstring.md
  - 通用规则包标准:
      - 什么是规则包?: Standard/what-is-rule-package.md
      - 为什么要做规则包?: Standard/why-rule-package.md
      - 什么是通用规则包标准?: Standard/what-is-standard.md
      - 术语表(草案):
          - setting 背景: Standard/Term/setting.md
          - scenario 剧本: Standard/Term/scenario.md
          - duration 时长:
              - Standard/Term/duration/index.md
              - sene 场: Standard/Term/duration/sene.md
              - module 模组: Standard/Term/duration/module.md
              - campaign 战役: Standard/Term/duration/campaign.md
          - DefaultDice 默认骰子:
              - Standard/Term/DefaultDice/index.md
              - _sides 骰子面数: Standard/Term/DefaultDice/_sides.md
              - _counts 骰子个数: Standard/Term/DefaultDice/_counts.md
          - check 检定:
              - Standard/Term/check/index.md
              - ability 检定: Standard/Term/check/ability.md
          - PlayerCard 人物卡:
              - Standard/Term/PlayerCard/index.md
  - CLI 参考:
      - "CLI Reference": CLI/index.md
  - API 参考:
      - "API Reference": API/index.md
  - 其他帮助:
      - "术语表一览": Help/TermList.md
      - "Python 技巧": Help/PythonSkill.md
      - "图标、图例、注释说明": Help/emoji.md
  - 博客:
      - blog/index.md
  - 日志:
      - changelog.md

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - "https://samuelcolvin.github.io/mkdocs-run-code/run_code_main.js"
