[project]
name = "infini"
version = "2.0.0-alpha.1"
description = "Infini 核心标准文本输入输出模块"
authors = [
<<<<<<< HEAD
=======
    { name = "简律纯", email = "leader@hydroroll.team" },
>>>>>>> 8dd7d3fe24acdbb7f52aa245f5f44991f3a44f46
    { name = "苏向夜", email = "fu050409@163.com" },
    { name = "简律纯", email = "i@jyunko.cn" },
]
dependencies = [
    "rich>=13.7.0",
]
requires-python = ">=3.10"
readme = "README.md"
license = { text = "MIT" }

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.pdm]
distribution = true

[tool.pdm.dev-dependencies]
test = [
    "pytest>=7.4.4",
]
