[project]
name = "HydroRollCore"
version = "0.1.2"
description = "The Core of HydroRoll, The Loader of your rules packages."
authors = [{ name = "简律纯", email = "i@jyunko.cn" }]
dependencies = [
    "mkdocs>=1.5.3",
    "mkdocs-material>=9.4.4",
    "mkdocs-blog-plugin>=0.25",
    "mkdocs-git-revision-date-localized-plugin>=1.2.0",
    "mkdocs-git-authors-plugin>=0.7.2",
    "mkdocs-material-extensions>=1.2",
    "neoteroi-mkdocs>=1.0.4",
    "pillow>=10.0.1",
    "cairosvg>=2.7.1",
    "mkdocs-git-committers-plugin-2>=1.2.0",
    "lxml>=4.9.3",
    "mkdocs-minify-plugin>=0.7.1",
    "mkdocs-rss-plugin>=1.8.0",
    "mkdocs-redirects>=1.2.1",
]
requires-python = ">=3.8"
readme = "README.md"
license = { text = "MIT" }


[project.scripts]
HydroRollCore = "HydroRollCore.cli:Cli.parse_args"
HRC = "HydroRollCore.cli:Cli.parse_args"

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

