[project]
name = "infini"
version = "1.0.4"
description = "Infini 核心标准输入输出模块"
authors = [{ name = "简律纯", email = "i@jyunko.cn" }, { name = "苏向夜", email = "fu050409@163.com" }]
dependencies = ["reportlab[pycairo]>=4.0.5", "pydantic>=2.4.2", "loguru>=0.7.2"]
requires-python = ">=3.9"
readme = "README.md"
license = { text = "MIT" }

[tool.pdm.dev-dependencies]
dev = [
    "mkdocs>=1.5.3",
    "mkdocs-material[imaging]>=9.4.4",
    "mkdocs-blog-plugin>=0.25",
    "mkdocs-git-revision-date-localized-plugin>=1.2.0",
    "mkdocs-git-authors-plugin>=0.7.2",
    "mkdocs-material-extensions>=1.2",
    "neoteroi-mkdocs>=1.0.4",
    "pillow~=9.4",
    "cairosvg>=2.7.1",
    "mkdocs-git-committers-plugin-2>=1.2.0",
    "lxml>=4.9.3",
    "mkdocs-minify-plugin>=0.7.1",
    "mkdocs-rss-plugin>=1.8.0",
    "mkdocs-redirects>=1.2.1",
    "mike>=1.1.2",
    "mkdocstrings>=0.23.0",
]

[project.scripts]
infini = "infini.cli:Cli.parse_args"
ifi = "infini.cli:Cli.parse_args"

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
