[tool.poetry]
name = "HydroRollCore"
version = "0.0.1"
authors = ["简律纯 <i@jyunko.cn>"]
description = "Core of HydroRoll."
readme = "README.md"
keywords = ["HydroRoll", "core"]
homepage = "https://github.com/HydoRoll-Team/HydroRollCore"
packages = [
    { include = "HydroRollCore", from = "." }
]

[tool.poetry.dependencies]
python = ">=3.8"

[tool.poetry.plugins."poetry-plugin"]
class = "poetry_plugin.plugin.Plugin"

[tool.poetry.scripts]
HydroRollCore = "HydroRollCore.main:main"

[tool.poetry.group.dev.dependencies]
black = "^23.1.0"
isort = "^5.12.0"
pre-commit = "^3.1.0"
pre-commit-hooks = "^4.4.0"

[tool.black]
target-version = ["py38", "py39", "py310", "py311"]

[tool.isort]
profile = "black"
length_sort = true
skip_gitignore = true
force_sort_within_sections = true
src_paths = ["HydroRollCore", "tests"]
extra_standard_library = ["typing_extensions"]

[tool.pyright]
exclude = ["tests"]
pythonVersion = "3.8"
pythonPlatform = "All"
typeCheckingMode = "strict"
reportImportCycles = false
reportIncompatibleMethodOverride = false
reportMissingTypeArgument = false
reportMissingTypeStubs = false
reportUnknownArgumentType = false
reportUnknownLambdaType = false
reportUnknownMemberType = false
reportUnknownParameterType = false
reportUnknownVariableType = false
reportUnnecessaryIsInstance = false

[tool.pydantic-pycharm-plugin]
ignore-init-method-arguments = true

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
