[tool.pdm.build]
includes = ["HydroRollCore"]
[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[project]
name = "HydroRollCore"
version = "0.0.1"
description = "Core of HydroRoll."
authors = [
    {name = "简律纯", email = "i@jyunko.cn"},
]
dependencies = [
    "mkdocs>=1.5.3",
    "mkdocs-material>=9.4.2",
    "mkdocs-blog-plugin>=0.25",
    "mkdocs-git-revision-date-localized-plugin>=1.2.0",
    "mkdocs-git-authors-plugin>=0.7.2",
    "mkdocs-material-extensions>=1.2",
    "neoteroi-mkdocs>=1.0.4",
    "pillow>=10.0.1",
    "cairosvg>=2.7.1",
    "mkdocs-git-committers-plugin-2>=1.2.0",
    "lxml>=4.9.3",
    "mkdocs-minify-plugin>=0.7.1",
    "mkdocs-rss-plugin>=1.8.0",
    "mkdocs-redirects>=1.2.1",
]
requires-python = ">=3.8"
readme = "README.md"
license = {text = "MIT"}
keywords = ["HydroRoll", "core"]

[project.urls]
homepage = "https://github.com/HydoRoll-Team/HydroRollCore"