name: Build Windows Executable

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          cache: pip
          architecture: x64
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r ./requirements_win.txt
      - name: Run packing
        run: |
          pyinstaller ./main.spec
      - name: Run artifact
        run: |
          mkdir HydroRollCore-Win
          cp ./dist/main.exe ./HydroRollCore-win/HydroRollCore.exe
      - name: Packing HydroRollCore-Win
        uses: actions/upload-artifact@v3
        with:
          name: HydroRollCore-Win-old-origin
          path: ./HydroRollCore-Win
      - name: Ready for Packing
        run: |
          mkdir ./HydroRollCore-Win/lib
          curl -L https://github.com/Mrs4s/go-cqhttp/releases/latest/download/go-cqhttp_windows_amd64.exe -o ./HydroRollCore-Win/lib/go-cqhttp.exe
      - name: Packing HydroRollCore-Win-with-lib
        uses: actions/upload-artifact@v3
        with:
          name: HydroRollCore-Win-old
          path: ./HydroRollCore-Win
