name: build Pages
on:
  push:
    branches:
      - master
      - main
    paths:
      - "*.md"
      - docs/**
      - .github/workflows/pages.yml

permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: |
          cp CHANGELOG.md docs/changelog.md
          pip install -r requirements.txt
          pip install pdm mike mkdocstrings
          pdm install

      - name: Build Documentation
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git fetch origin gh-pages:gh-pages
          pdm run mike deploy --update-aliases dev
          git push origin gh-pages
